image=~/Pictures/Wallpapers/everforest-light.*
scaling=fill
ignore-empty-password
show-failed-attempts
fade-in=0.2

clock
timestr=%H:%M
datestr=%A, %B %e

indicator
indicator-radius=160
indicator-thickness=12
font=SF Pro Rounded
font-size=72

# Base (idle)
ring-color=00000000
inside-color=00000000
line-color=00000000
separator-color=00000000
text-color=5c6a72

# Typing
key-hl-color=9da9a0
bs-hl-color=f85552

# Cleared
ring-clear-color=00000000
inside-clear-color=00000000
line-clear-color=00000000
text-clear-color=5c6a72

# Verifying
ring-ver-color=35a77c
inside-ver-color=fdf6e3cc
line-ver-color=00000000
text-ver-color=5c6a72

# Wrong
ring-wrong-color=f85552
inside-wrong-color=fdf6e3cc
line-wrong-color=00000000
text-wrong-color=5c6a72