image=~/Pictures/Wallpapers/everforest.*
scaling=fill
ignore-empty-password
show-failed-attempts
fade-in=0.2

clock
timestr=%H:%M
datestr=%A, %B %e

indicator
indicator-radius=160
indicator-thickness=12

font=SF Pro Rounded
font-size=72

# Idle
ring-color=00000000
inside-color=00000000
line-color=00000000
separator-color=00000000
text-color=d3c6aa

# Typing
key-hl-color=9da9a0
bs-hl-color=e67e80

# Cleared
ring-clear-color=00000000
inside-clear-color=00000000
line-clear-color=00000000
text-clear-color=d3c6aa

# Verifying
ring-ver-color=7fbbb3
inside-ver-color=1e2326cc
line-ver-color=00000000
text-ver-color=d3c6aa

# Wrong
ring-wrong-color=e67e80
inside-wrong-color=1e2326cc
line-wrong-color=00000000
text-wrong-color=d3c6aa