image=~/Pictures/Wallpapers/nord.*
scaling=fill
ignore-empty-password
show-failed-attempts
fade-in=0.2

clock
timestr=%H:%M
datestr=%A, %B %e

indicator
indicator-radius=160
indicator-thickness=12
font=SF Pro Rounded
font-size=72

# Base (idle)
ring-color=00000000
inside-color=00000000
line-color=00000000
separator-color=00000000
text-color=eceff4

# Typing
key-hl-color=9aa7b4
bs-hl-color=bf616a

# Cleared
ring-clear-color=00000000
inside-clear-color=00000000
line-clear-color=00000000
text-clear-color=eceff4

# Verifying
ring-ver-color=88c0d0
inside-ver-color=2e3440cc
line-ver-color=00000000
text-ver-color=eceff4

# Wrong
ring-wrong-color=bf616a
inside-wrong-color=2e3440cc
line-wrong-color=00000000
text-wrong-color=eceff4