image=~/Pictures/Wallpapers/untitled.*
scaling=fill
ignore-empty-password
show-failed-attempts
fade-in=0.2

clock
timestr=%H:%M
datestr=%A, %B %e

indicator
indicator-radius=160
indicator-thickness=12
font=SF Pro Rounded
font-size=72

# Base (idle)
ring-color=00000000
inside-color=00000000
line-color=00000000
separator-color=00000000
text-color=e1e1e1

# Typing
key-hl-color=c08da5
bs-hl-color=927ba7

# Cleared
ring-clear-color=00000000
inside-clear-color=00000000
line-clear-color=00000000
text-clear-color=e1e1e1

# Verifying
ring-ver-color=927ba7
inside-ver-color=0d0d0dcc
line-ver-color=00000000
text-ver-color=e1e1e1

# Wrong
ring-wrong-color=c08da5
inside-wrong-color=0d0d0dcc
line-wrong-color=00000000
text-wrong-color=e1e1e1